# Generated by Django 4.2.6 on 2023-11-10 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('height', models.PositiveIntegerField(verbose_name='Product height in cm')),
                ('width', models.PositiveIntegerField(verbose_name='Product width in cm')),
                ('depth', models.PositiveIntegerField(verbose_name='Product depth in cm')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Product weight in kg')),
                ('quantity', models.PositiveIntegerField()),
                ('min_quantity', models.PositiveIntegerField()),
                ('max_quantity', models.PositiveIntegerField()),
                ('last_update_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RFIDGate',
            fields=[
                ('public_id', models.CharField(max_length=32, unique=True)),
                ('internal_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('scan_action', models.IntegerField(choices=[(0, 'Receive'), (1, 'Dispatch')], verbose_name='Action taken on scanned products')),
                ('last_connection_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(choices=[(0, 'Receive'), (1, 'Dispatch')], verbose_name='Action taken when product was scanned')),
                ('quantity', models.PositiveIntegerField(verbose_name='Number of instances of product scanned')),
                ('time', models.DateTimeField(verbose_name='Time at which product was scanned')),
                ('gate_internal_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.rfidgate', verbose_name='Internal ID of gate that scanned product')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.product', verbose_name='ID of scanned product')),
            ],
        ),
    ]
