# Generated by Django 4.2.6 on 2023-11-10 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='last_update_time',
        ),
        migrations.AlterField(
            model_name='rfidgate',
            name='last_connection_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scanevent',
            name='gate_internal_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.rfidgate', verbose_name='Internal ID of gate that scanned product'),
        ),
        migrations.AlterField(
            model_name='scanevent',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.product', verbose_name='ID of scanned product'),
        ),
    ]
