# Generated by Django 4.2.6 on 2023-11-14 01:45

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_product_last_update_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('code', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Product code')),
                ('scan_in_time', models.DateTimeField(verbose_name='Time when product instance was scanned in')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='scanevent',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=dashboard.models.product_image_path),
        ),
        migrations.AddField(
            model_name='scanevent',
            name='new_quantity',
            field=models.PositiveIntegerField(default=None, verbose_name='New quantity of product in warehouse after scan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rfidgate',
            name='internal_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Gate ID that is used internally to identify gates; should not be exposed to user'),
        ),
        migrations.AlterField(
            model_name='rfidgate',
            name='last_connection_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Time of most recent connection'),
        ),
        migrations.AlterField(
            model_name='rfidgate',
            name='public_id',
            field=models.CharField(max_length=32, unique=True, verbose_name='Gate ID that can be exposed to users'),
        ),
    ]
