# Generated by Django 4.2.6 on 2023-11-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Weight in kg'),
        ),
    ]
