# Use the slim Python runtime to reduce container image size
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app
COPY ./requirements.txt /app/requirements.txt

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Set environment variables for Django
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Container file structure:
# app
# ├── ics
# └── dashboard

COPY ./ics /app/ics
COPY ./dashboard/build/web /app/dashboard

# Expose the port the app runs on
EXPOSE 8000

# Run django app
CMD ["python", "ics/manage.py", "runserver", "0.0.0.0:8000"]

